/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan
 */
public class Order extends javax.swing.JDialog {

    /**
     * Creates new form Order
     */
    //initialize menu from 'Main_Menu'
    HashMap<String, Double> menu;
    //for this table only
    HashMap<String, Integer> orders = new HashMap<>();

    private double price = 0.0;
    private int id; 
    private Map<Integer, Order> customers;
    double discount = 1;
    
    public Order(java.awt.Frame parent, boolean modal, HashMap<Integer,Order> map, int id) {
        super(parent, modal);
        initComponents();
        this.setSize(800,600);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Main_Menu mmob = new Main_Menu("");
        this.menu = mmob.getMenu();
        this.customers = map;
        this.id = id;
    }
    
    public int getId(){
        return this.id;
    }
    
    public double getPrice(){
        return this.price;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Finish = new javax.swing.JButton();
        Total_Price = new javax.swing.JLabel();
        Total_Price_Text = new javax.swing.JTextField();
        See_Price = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Five_Off = new javax.swing.JButton();
        Ten_Off = new javax.swing.JButton();
        Fifteen_Off = new javax.swing.JButton();
        Main_Order_Screen = new javax.swing.JTabbedPane();
        Drinks_Snacks = new javax.swing.JPanel();
        Water_L = new javax.swing.JLabel();
        Soft_Drink_L = new javax.swing.JLabel();
        Bubble_Tea_L = new javax.swing.JLabel();
        Special_Drink_L = new javax.swing.JLabel();
        Water_Price = new javax.swing.JLabel();
        Item2_D = new javax.swing.JLabel();
        Item3_D = new javax.swing.JLabel();
        Item4_D = new javax.swing.JLabel();
        Water_Num = new javax.swing.JTextField();
        Soft_Drink_Num = new javax.swing.JTextField();
        Bubble_Tea_Num = new javax.swing.JTextField();
        Special_Drink_Num = new javax.swing.JTextField();
        Fries_L = new javax.swing.JLabel();
        Favor_Egg_L = new javax.swing.JLabel();
        Fries_Price = new javax.swing.JLabel();
        Favor_Egg_Price = new javax.swing.JLabel();
        Fries_Num = new javax.swing.JTextField();
        Favor_Egg_Num = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Main_Entree = new javax.swing.JPanel();
        Chicken_Broccolini_L = new javax.swing.JLabel();
        Water_Price1 = new javax.swing.JLabel();
        Chicken_Broccolini_Num = new javax.swing.JTextField();
        Shrimp_Fried_Rice_L = new javax.swing.JLabel();
        Shrimp_Fried_Rice_Price = new javax.swing.JLabel();
        Shrimp_Fried_Rice_Num = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Finish.setText("Finish Order");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        Total_Price.setText("Total Price $");

        Total_Price_Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_Price_TextActionPerformed(evt);
            }
        });

        See_Price.setText("See Price");
        See_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                See_PriceActionPerformed(evt);
            }
        });

        jLabel5.setText("Discount");

        Five_Off.setText("5% Off");
        Five_Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Five_OffActionPerformed(evt);
            }
        });

        Ten_Off.setText("10% Off");
        Ten_Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ten_OffActionPerformed(evt);
            }
        });

        Fifteen_Off.setText("15% Off");
        Fifteen_Off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fifteen_OffActionPerformed(evt);
            }
        });

        Drinks_Snacks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Water_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Water_L.setText("Water");
        Drinks_Snacks.add(Water_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 58, -1));

        Soft_Drink_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Soft_Drink_L.setText("Soft Drink");
        Drinks_Snacks.add(Soft_Drink_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, -1, -1));

        Bubble_Tea_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bubble_Tea_L.setText("Bubble Tea");
        Drinks_Snacks.add(Bubble_Tea_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 63, -1, -1));

        Special_Drink_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Special_Drink_L.setText("Special Drink");
        Drinks_Snacks.add(Special_Drink_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, -1, -1));

        Water_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Water_Price.setText("$1");
        Drinks_Snacks.add(Water_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 11, -1, -1));

        Item2_D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Item2_D.setText("$1.5");
        Drinks_Snacks.add(Item2_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 37, -1, -1));

        Item3_D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Item3_D.setText("$2.5");
        Drinks_Snacks.add(Item3_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 63, -1, -1));

        Item4_D.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Item4_D.setText("$3");
        Drinks_Snacks.add(Item4_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 89, -1, -1));
        Drinks_Snacks.add(Water_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 11, 72, -1));

        Soft_Drink_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Soft_Drink_NumActionPerformed(evt);
            }
        });
        Drinks_Snacks.add(Soft_Drink_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 37, 72, -1));
        Drinks_Snacks.add(Bubble_Tea_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 63, 72, -1));
        Drinks_Snacks.add(Special_Drink_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 89, 72, -1));

        Fries_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fries_L.setText("Fries");
        Drinks_Snacks.add(Fries_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 11, -1, -1));

        Favor_Egg_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Favor_Egg_L.setText("Favor Egg");
        Drinks_Snacks.add(Favor_Egg_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 37, -1, -1));

        Fries_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fries_Price.setText("$4");
        Drinks_Snacks.add(Fries_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 11, -1, -1));

        Favor_Egg_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Favor_Egg_Price.setText("$1.5");
        Drinks_Snacks.add(Favor_Egg_Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 37, -1, -1));
        Drinks_Snacks.add(Fries_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 11, 72, -1));
        Drinks_Snacks.add(Favor_Egg_Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 37, 72, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/sky.png"))); // NOI18N
        Drinks_Snacks.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 460));

        Main_Order_Screen.addTab("Drinks and Snacks", Drinks_Snacks);

        Main_Entree.setLayout(null);

        Chicken_Broccolini_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Chicken_Broccolini_L.setText("Chicken Broccolini");
        Main_Entree.add(Chicken_Broccolini_L);
        Chicken_Broccolini_L.setBounds(10, 11, 109, 17);

        Water_Price1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Water_Price1.setText("$8");
        Main_Entree.add(Water_Price1);
        Water_Price1.setBounds(145, 11, 16, 17);
        Main_Entree.add(Chicken_Broccolini_Num);
        Chicken_Broccolini_Num.setBounds(191, 11, 72, 20);

        Shrimp_Fried_Rice_L.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Shrimp_Fried_Rice_L.setText("Shrimp Fried Rice");
        Main_Entree.add(Shrimp_Fried_Rice_L);
        Shrimp_Fried_Rice_L.setBounds(10, 37, 105, 17);

        Shrimp_Fried_Rice_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Shrimp_Fried_Rice_Price.setText("$9.5");
        Main_Entree.add(Shrimp_Fried_Rice_Price);
        Shrimp_Fried_Rice_Price.setBounds(145, 37, 28, 17);

        Shrimp_Fried_Rice_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Shrimp_Fried_Rice_NumActionPerformed(evt);
            }
        });
        Main_Entree.add(Shrimp_Fried_Rice_Num);
        Shrimp_Fried_Rice_Num.setBounds(191, 37, 72, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/sky.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        Main_Entree.add(jLabel2);
        jLabel2.setBounds(0, 0, 620, 460);

        Main_Order_Screen.addTab("Main Entree", Main_Entree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(693, 693, 693)
                .addComponent(Ten_Off))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(Finish)
                .addGap(18, 18, 18)
                .addComponent(Total_Price))
            .addGroup(layout.createSequentialGroup()
                .addGap(648, 648, 648)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(693, 693, 693)
                .addComponent(Fifteen_Off))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(See_Price))
            .addGroup(layout.createSequentialGroup()
                .addGap(693, 693, 693)
                .addComponent(Five_Off, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Main_Order_Screen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(Total_Price_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Ten_Off)
                .addGap(438, 438, 438)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Finish)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Total_Price))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Fifteen_Off))
            .addGroup(layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(See_Price))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Five_Off))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Main_Order_Screen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(502, 502, 502)
                .addComponent(Total_Price_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Total_Price_TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_Price_TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_Price_TextActionPerformed

    private void See_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_See_PriceActionPerformed
        price = 0;
        try{
            //Drinks and Snacks Tab
            if(!Water_Num.getText().isEmpty()){
                orders.put("Water", Integer.parseInt(Water_Num.getText()));   
            }
            if(!Soft_Drink_Num.getText().isEmpty()){
                orders.put("Soft Drink", Integer.parseInt(Soft_Drink_Num.getText()));
            }
            if(!Bubble_Tea_Num.getText().isEmpty()){
                orders.put("Bubble Tea", Integer.parseInt(Bubble_Tea_Num.getText()));
            }
            if(!Special_Drink_Num.getText().isEmpty()){
                orders.put("Special Drink", Integer.parseInt(Special_Drink_Num.getText()));
            }
            if(!Fries_Num.getText().isEmpty()){
                orders.put("Fries", Integer.parseInt(Fries_Num.getText()));
            }
            if(!Favor_Egg_Num.getText().isEmpty()){
                orders.put("Favor Egg", Integer.parseInt(Favor_Egg_Num.getText()));
            }
            //Main Entree Tab
            if(!Chicken_Broccolini_Num.getText().isEmpty()){
                orders.put("Chicken Broccolini", Integer.parseInt(Chicken_Broccolini_Num.getText()));
            }
            if(!Shrimp_Fried_Rice_Num.getText().isEmpty()){
                orders.put("Shrimp Fried Rice", Integer.parseInt(Shrimp_Fried_Rice_Num.getText()));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Input Error","Error",JOptionPane.WARNING_MESSAGE);
        }
           
        for (String it : orders.keySet()) {
            price = price + (menu.get(it)*orders.get(it));
        }
        price *= discount;
        Total_Price_Text.setText(price+"");
    }//GEN-LAST:event_See_PriceActionPerformed
    public void update_Price(java.awt.event.ActionEvent evt){
        this.See_PriceActionPerformed(evt);
    }
    
    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        // TODO add your handling code here:
        price = 0;
        
        this.See_PriceActionPerformed(evt);
        
        this.customers.put(id, this);
        this.setVisible(false);
    }//GEN-LAST:event_FinishActionPerformed

    private void Five_OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Five_OffActionPerformed
        // TODO add your handling code here:
        discount = 0.95;
    }//GEN-LAST:event_Five_OffActionPerformed

    private void Ten_OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ten_OffActionPerformed
        // TODO add your handling code here:
        discount = 0.9;

    }//GEN-LAST:event_Ten_OffActionPerformed

    private void Fifteen_OffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fifteen_OffActionPerformed
        // TODO add your handling code here:
        discount = 0.85;
    }//GEN-LAST:event_Fifteen_OffActionPerformed

    private void Soft_Drink_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Soft_Drink_NumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Soft_Drink_NumActionPerformed

    private void Shrimp_Fried_Rice_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Shrimp_Fried_Rice_NumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Shrimp_Fried_Rice_NumActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Bubble_Tea_L;
    private javax.swing.JTextField Bubble_Tea_Num;
    private javax.swing.JLabel Chicken_Broccolini_L;
    private javax.swing.JTextField Chicken_Broccolini_Num;
    private javax.swing.JPanel Drinks_Snacks;
    private javax.swing.JLabel Favor_Egg_L;
    private javax.swing.JTextField Favor_Egg_Num;
    private javax.swing.JLabel Favor_Egg_Price;
    private javax.swing.JButton Fifteen_Off;
    private javax.swing.JButton Finish;
    private javax.swing.JButton Five_Off;
    private javax.swing.JLabel Fries_L;
    private javax.swing.JTextField Fries_Num;
    private javax.swing.JLabel Fries_Price;
    private javax.swing.JLabel Item2_D;
    private javax.swing.JLabel Item3_D;
    private javax.swing.JLabel Item4_D;
    private javax.swing.JPanel Main_Entree;
    private javax.swing.JTabbedPane Main_Order_Screen;
    private javax.swing.JButton See_Price;
    private javax.swing.JLabel Shrimp_Fried_Rice_L;
    private javax.swing.JTextField Shrimp_Fried_Rice_Num;
    private javax.swing.JLabel Shrimp_Fried_Rice_Price;
    private javax.swing.JLabel Soft_Drink_L;
    private javax.swing.JTextField Soft_Drink_Num;
    private javax.swing.JLabel Special_Drink_L;
    private javax.swing.JTextField Special_Drink_Num;
    private javax.swing.JButton Ten_Off;
    private javax.swing.JLabel Total_Price;
    private javax.swing.JTextField Total_Price_Text;
    private javax.swing.JLabel Water_L;
    private javax.swing.JTextField Water_Num;
    private javax.swing.JLabel Water_Price;
    private javax.swing.JLabel Water_Price1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    
}
